# Generated by Django 5.2.3 on 2025-06-25 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marks",
            name="max_marks",
            field=models.IntegerField(default=100),
        ),
    ]
