# Generated by Django 5.2.3 on 2025-06-26 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marks", "0002_alter_marks_max_marks"),
    ]

    operations = [
        migrations.RenameField(
            model_name="regulation",
            old_name="passout_year",
            new_name="batch_year",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="semester",
            new_name="current_semester",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="year",
            new_name="current_year",
        ),
        migrations.AddField(
            model_name="student",
            name="admission_year",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
