# Generated by Django 5.2.4 on 2025-07-20 11:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marks", "0004_rename_batch_year_regulation_passout_year_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
